### ISSUE TITLE
No courses or tracks found!

### ISSUE THREAD

**Issue by bozhang-PhD** [TRoboto/datacamp-downloader#7]
find the subscription, but can't find my courses and tracks. thank you for your help!
![image](https://user-images.githubusercontent.com/17062534/80836184-10741b80-8ba9-11ea-8346-b84d03baf4b2.png)

**Comment by TRoboto** [comment]
You can only list and download your completed tracks or courses. Please open [Datacamp](https://datacamp.com) and check your profile by clicking on `My Account` at the top right and click on `My Profile`. Scroll down to see your completed tracks or courses. If you have any completed ones, please provide us, if possible, with a link to your Datacamp profile so that we can check what's wrong with the tool.

**Comment by coesite** [comment]
Thank you very much. Yes, there this no completed tracks and courses under my Account.  Thank you for your wonderful tools.

**Comment by clarevoyance** [comment]
seems like datacamp no longer makes it possible. I had managed to do this a couple of weeks ago but now it just says "Please provide a valid token!"

**Comment by TRoboto** [comment]
I updated the tool just now, please try it and send feedback if possible

**Comment by noAudio** [comment]
Hey TRoboto, is there a way to download tracks/courses you haven't completed? I don't have a stable connection and would have an easier time doing the courses offline. Thanks!

**Comment by noAudio** [comment]
Hey TRoboto, is there a way to download tracks/courses you haven't completed? I don't have a stable connection and would have an easier time doing the courses offline. Thanks!

**Comment by TRoboto** [comment]
Hey, 
Unfortunately, the tool does not support downloading incomplete tracks/courses. Hope you a happy learning path!

Closing this issue since it has been solved! If you want to request features, please start a new issue.
